### ISSUE TITLE
Does not auto clear whitespaces after comments

### ISSUE THREAD

**Issue by Resike** [p3lim/sublime-strip-whitespace-lines#1]
Examples:
```Lua
-- This is a very sexy comment  [insert a lof of nasty whitespace here]
--[[This is a very sexy nested comment]]  [insert a lof of nasty whitespace here]
--[=[This is a very sexy level 1 nested comment]=] [insert a lof of nasty whitespace here]
```

**Comment by p3lim** [comment]
This is intended.

The default option `trim_trailing_white_space_on_save` in Sublime Text strips the whitespace off the end of any line, while this plugin intends to only strip it off lines consisting of only whitespace.

If you want that behavior you exemplified you'd be better off using that option instead.

I can see that the readme was not explaining this well, I'll update it.

**Comment by p3lim** [comment]
As a sidenote, I used the default option for a long time, but ever since I started doing in-line documentation using Markdown as markup I needed to keep the whitespace at the end of the lines (two blank spaces at the end of the line in Markdown indicates a newline), hence this plugin was made in frustration.

I also made the plugin [highlight-trailing-whitespace](https://github.com/p3lim/sublime-highlight-trailing-whitespace) to accompany this plugin so that I'm aware of the trailing whitespaces as well.

**Comment by Resike** [comment]
I see, didnt know there was an options for trim_trailing_white_space_on_save, i prefer that one. I will still use the highlight one.
